- package.json
> [figma]:update to 0.0.17

- package.json
> [figma]:update to 0.0.20

- package.json
> [figma]:update to 0.0.24

- package.json
> [figma]:update to 0.0.25

- package.json
> [figma]:update to 0.0.26

- package.json
> [figma]:update to 0.0.27

- package.json
> [figma]:update to 0.0.28

- package.json
> [figma]:update to 0.0.29

- package.json
> [figma]:update to 0.0.30

- package.json
> [figma]:update to 0.0.31

- package.json
> [figma]:update to 0.0.32

- package.json
> [figma]:update to 0.0.33

- package.json
+icon_subscribe_24;+icon_subscribed_24
> [figma]:update to 0.0.37

- package.json
> [figma]:update to 0.0.39

- package.json
> [figma]:update to 0.0.40

- package.json
> [figma]:update to 0.0.41

- package.json
> [figma]:update to 0.0.42

- package.json
> [figma]:update to 0.0.43

- package.json
+colorful_icon_chain_polygon_scalable&colorful_icon_chain_arbitrum_scalable
> [figma]:update to 0.0.44

- package.json
> [figma]:update to 0.0.45

- package.json
> [figma]:update to 0.0.46

- package.json
> [figma]:update to 0.0.47

- package.json
> [figma]:update to 0.0.48

- package.json
> [figma]:update to 0.0.49

- package.json
> [figma]:update to 0.0.50

- package.json
> [figma]:update to 0.0.51

- package.json
> [figma]:update to 0.0.52

- package.json
> [figma]:update to 0.0.53

- package.json
> [figma]:update to 0.0.54

- package.json
> [figma]:update to 0.0.55

- package.json
> [figma]:update to 0.0.56

- package.json
> [figma]:update to 0.0.57

- package.json
> [figma]:update to 0.0.58

- package.json
> [figma]:update to 0.0.59

- package.json
> [figma]:update to 0.0.60

- package.json
> [figma]:update to 0.0.62

- package.json
> [figma]:update to 0.0.63

- package.json
> [figma]:update to 0.0.64

- package.json
> [figma]:update to 0.0.65

- package.json
> [figma]:update to 0.0.66

- package.json
colorful_icon_chain_Xterio_scalable
> [figma]:update to 0.0.67

- package.json
colorful_icon_chain_xterio_scalable
> [figma]:update to 0.0.68

- package.json
colorful_icon_chain_xterio_scalable
> [figma]:update to 0.0.69

- package.json
+colorful_icon_chain_base_scalable
> [figma]:update to 0.0.70

- package.json
colorful_icon_chain_xterio_bsc_scalable,
colorful_icon_chain_xterio_eth_scalable
> [figma]:update to 0.0.71

- package.json
> [figma]:update to 0.0.72

- package.json
> [figma]:update to 0.0.73

- package.json
icon_fullscreen_16     icon_gallery_16
> [figma]:update to 0.0.74

- package.json
icon_fullscreen_16    icon_gallery_16
> [figma]:update to 0.0.75

- package.json
> [figma]:update to 0.0.76

- package.json
> [figma]:update to 0.0.77

- package.json
> [figma]:update to 0.0.78

- package.json
> [figma]:update to 0.0.79

- package.json
> [figma]:update to 0.1.23

- package.json
新增两个图标：icon_small_refresh_12 和 icon_send_scalable
> [figma]:update to 0.1.25

- package.json
icon_token_default 三个尺寸：16、24、32
> [figma]:update to 0.1.28

- package.json
新增xter token: icon_token_xter_scalable
> [figma]:update to 0.1.30

- package.json
> [figma]:update to 0.1.31

- package.json
> [figma]:update to 0.1.32

- package.json
> [figma]:update to 0.1.33

- package.json
> [figma]:update to 0.1.34

- package.json
> [figma]:update to 0.1.35
